import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import deved from "../public/logohb.svg";
import { IconButton } from "@material-tailwind/react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>HB Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-sky-500">
        <section className="">
          <nav className="py-10 mb-12 flex justify-between">
            <a
              className="animate-bounce cursor-pointer dark:bg-white rounded-full p-1"
              href="../"
            >
              <Image src={deved} width="30%" height="30%" />
            </a>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl text-sky-500 dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-sky-500 text-white px-4 py-2 rounded-md ml-8 dark:bg-white dark:text-sky-500"
                  href="#"
                >
                  My Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h3 className="text-2xl py-2 md:text-3xl">BrandFolio</h3>
            <IconButton>
              {" "}
              <i className="fas fa-heart" />{" "}
            </IconButton>
            <p className="text-md py-1 leading-8 mb-1 text-gray-700 md:text-xl max-w-lg mx-auto">
            It’s important that companies have a consistent brand design across all of their touchpoints, so that they can reinforce their brand image and connect with their audience. This can help them leave a lasting impression.
            </p>
          </div>
        </section>
        <section class="">
          <div class="container px-1 py-5 pb-20 mt-0 mx-auto items-center ">
            <div class="grid grid-cols-4 grid-rows-4 grid-flow-col gap-4">
              <div class="bg-sky-500 w-full row-span-2 dark:bg-white rounded p-1">
                <img
                  src="../src/brandingimages/brandingimage3.png"
                  alt="Photo by Claudio Schwarz on Unsplash"
                  class="hover:scale-105 ease-in duration-500 inset-0 h-full w-full object-cover object-center rounded opacity-85 hover:opacity-100"
                />
                <div className="cursor-pointer ">❤️</div>  
              </div>
              <div class="bg-sky-500 w-full col-span-2 row-span-2 dark:bg-white rounded p-1">
                <img
                  src="../src/brandingimages/brandingimage1.png"
                  alt="Photo by Claudio Schwarz on Unsplash"
                  class="hover:scale-105 ease-in duration-500 inset-0 h-full w-full object-cover object-center rounded opacity-85 hover:opacity-100 "
                />
                <div className="cursor-pointer ">❤️</div>
              </div>
              <div class="bg-sky-500 w-full dark:bg-white rounded p-1 ">
                <img
                  src="../src/brandingimages/brandingimage7.png"
                  alt="Photo by Claudio Schwarz on Unsplash"
                  class="hover:scale-105 ease-in duration-500 inset-0 h-full w-full object-cover object-center rounded opacity-85 hover:opacity-100 "
                />
                <div className="cursor-pointer ">❤️</div>
              </div>
              <div class="bg-sky-500 w-full dark:bg-white rounded p-1">
                <img
                  src="../src/brandingimages/brandingimage4.png"
                  alt="Photo by Claudio Schwarz on Unsplash"
                  class="hover:scale-105 ease-in duration-500 inset-0 h-full w-full object-cover object-center rounded opacity-85 hover:opacity-100 "
                />
                <div className="cursor-pointer ">❤️</div>
              </div> 
              <div class="bg-sky-500 w-full col-span-2 row-span-2 dark:bg-white rounded p-1">
                <img
                  src="../src/brandingimages/brandingimage2.png"
                  alt="Photo by Claudio Schwarz on Unsplash"
                  class="hover:scale-105 ease-in duration-500 inset-0 h-full w-full object-cover object-center rounded opacity-85 hover:opacity-100 "
                />
                <div className="cursor-pointer ">❤️</div>
              </div>

              <div class="bg-sky-500 w-full col-span-2 dark:bg-white rounded p-1">
                <img
                  src="../src/brandingimages/brandingimage5-1.png"
                  alt="Photo by Claudio Schwarz on Unsplash"
                  class="hover:scale-105 ease-in duration-500 inset-0 h-full w-full object-cover object-center rounded opacity-85 hover:opacity-100 "
                />
                <div className="cursor-pointer ">❤️</div>
              </div>
              <div class="bg-sky-500 w-full dark:bg-white rounded p-1">
                <img
                  src="../src/brandingimages/brandingimage6.png"
                  alt="Photo by Claudio Schwarz on Unsplash"
                  class="hover:scale-105 ease-in duration-500 inset-0 h-full w-full object-cover object-center rounded opacity-85 hover:opacity-100 "
                />
                <div className="cursor-pointer ">❤️</div>
              </div>
              <div class="bg-sky-500 w-full dark:bg-white rounded p-1">
                <img
                  src="../src/brandingimages/brandingimage8.png"
                  alt="Photo by Claudio Schwarz on Unsplash"
                  class="hover:scale-105 ease-in duration-500 inset-0 h-full w-full object-cover object-center rounded opacity-85 hover:opacity-100 "
                />
                <div className="cursor-pointer ">❤️</div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-sky-500 dark:bg-white">
        <div className="p-10  flex justify-center gap-20 text-white dark:text-sky-500">
          <h3>© 2022 Hassen Bouzidi | All Rights reserved</h3>
        </div>
      </footer>
    </div>
  );
}
