import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillInstagram,
  AiFillFacebook,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useEffect, useState } from "react";
/* import { ScrollToTop } from '../components/ScrollToTop'*/

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>HB Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-sky-500">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-bold dark:text-white">
              Welcome by me ;){" "}
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="  animate-bounce cursor-pointer text-2xl text-sky-500 dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-sky-500 text-white px-4 py-2 rounded-md ml-8 dark:bg-white dark:text-sky-500"
                  href="#"
                >
                  My Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-sky-500 font-bold md:text-6xl dark:text-white">
              Hassen Bouzidi
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Digital Designer</h3>
            <p className="text-md py-1 leading-8 text-gray-700 md:text-xl max-w-lg mx-auto">
              Serious steps in to the digit@l world, with optimistic
              perspectives, to participate in the visual communication
              revolution, in the maghrebian and arab countries.
            </p>
          </div>
          <div className="text-2xl flex justify-center gap-10 py-1 text-gray-500 dark:text-white">
            <AiFillTwitterCircle className="cursor-pointer" href="#" />
            <AiFillLinkedin className="cursor-pointer" href="#" />
            <AiFillYoutube className="cursor-pointer" href="#" />
            <AiFillInstagram className="cursor-pointer" href="#" />
            <AiFillFacebook className="cursor-pointer" href="#" />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-sky-500 rounded-full w-60 h-60 mt-20 overflow-hidden md:h-60 md:w-60 dark:from-white">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-center text-3xl font-bold py-10">
              Services I offer
            </h3>
            <p className="text-center px-5 text-md py-2 leading-8 text-gray-700 dark:text-white">
              {" "}
              Understanding the clients thinkings to build their project, by
              creating more then a brand, but a futurisme business career based
              on the powerful design that i do and the force of proposition
              witch i give to the clients
            </p>
          </div>
          <div className="lg:flex justify-center gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                className="mx-auto"
                src={design}
                width={100}
                height={100}
              />
              <h3 className="cursor-pointer text-lg font-medium pt-8 pb-2">
                <a href="#">Branding Concepts</a>
              </h3>
              <p className="py-2">
                Hold on... Think... Breath... Answer... Boom! Ready to get your
                super STRONG Branding
              </p>
              <h4 className="py-4 text-sky-500">Design tools I use</h4>
              <p className="text-gray-700 py-1 font-bold italic">
                Adobe Illustrator
              </p>
              <p className="text-gray-700 py-1 font-bold italic">
                Adobe Photoshop
              </p>
              <p className="text-gray-700 py-1 font-bold italic">
                Adobe Lightroom
              </p>
              <p className="text-gray-700 py-1 font-bold italic">
                Adobe Indesign
              </p>
              <div className="mt-10">
                <a
                  className="bg-sky-500 text-white px-4 py-2 rounded-md dark:bg-pink-600"
                  href="../branding"
                >
                  View Gallery
                </a>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image className="mx-auto" src={code} width={100} height={100} />
              <h3 className="cursor-pointer text-lg font-medium pt-8 pb-2">
                <a href="#">Websites Design</a>
              </h3>
              <p className="py-2">
                Ready to put your designed website between the gratests in the
                www. world
              </p>
              <h4 className="py-4 text-sky-500">Dev tools I use</h4>
              <p className="text-gray-700 py-1 font-bold italic">WordPress</p>
              <p className="text-gray-700 py-1 font-bold italic">Prestashop</p>
              <p className="text-gray-700 py-1 font-bold italic">React js</p>
              <div className="mt-10">
                <a
                  className="bg-sky-500 text-white px-4 py-2 rounded-md dark:bg-pink-600"
                  href="../websites"
                >
                  View Gallery
                </a>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                className="mx-auto"
                src={consulting}
                width={100}
                height={100}
              />
              <h3 className="cursor-pointer text-lg font-medium pt-8 pb-2">
                <a href="#">Interactive Videos</a>
              </h3>
              <p className="py-2">
                Ads, is a huge support for your brand, let's do some animations
                for U
              </p>
              <h4 className="py-4 text-sky-500">Vfx tools I use</h4>
              <p className="text-gray-700 py-1 font-bold italic">
                Adobe After Effects
              </p>
              <p className="text-gray-700 py-1 font-bold italic">
                Adobe Premier
              </p>
              <p className="text-gray-700 py-1 font-bold italic">
                Adobe Animate
              </p>
              <p className="text-gray-700 py-1 font-bold italic">
                Adobe Media Encoder
              </p>
              <div className="mt-10">
                <a
                  className="bg-sky-500 text-white px-4 py-2 rounded-md dark:bg-pink-600"
                  href="../videos"
                >
                  View Gallery
                </a>
              </div>
            </div>
          </div>
        </section>
        <section className="mb-0">
          <div>
            <h3 className="text-center text-3xl font-bold py-5">
              Quick Preview
            </h3>
            <p className="text-center px-5 text-md py-2 leading-8 text-gray-700 dark:text-white">
              {" "}
              Understanding the clients thinkings to build their project, by
              creating more then a brand, but a futurisme business career based
              on the powerful design that i do and the force of proposition
              witch i give to the clients
            </p>
            <p className="text-center px-5 text-md py-2 leading-8 text-gray-700 dark:text-white">
              {" "}
              Understanding the clients thinkings to build their project, by
              creating more then a brand, but a futurisme business career based
              on the powerful design that i do and the force of proposition
              witch i give to the clients
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap mb-20">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="hover:scale-110 transition delay-150 duration-300 ease-in-out cursor-pointer rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="hover:scale-110 transition delay-150 duration-300 ease-in-out cursor-pointer rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="hover:scale-110 transition delay-150 duration-300 ease-in-out cursor-pointer rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="hover:scale-110 transition delay-150 duration-300 ease-in-out cursor-pointer rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="hover:scale-110 transition delay-150 duration-300 ease-in-out cursor-pointer rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="hover:scale-110 transition delay-150 duration-300 ease-in-out cursor-pointer rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
          </div>
          <div></div>
        </section>
        <section className="bg-white rounded-t-lg dark:bg-white mt-0">
          <div className="py-10 lg:py-2 px-10 mx-auto max-w-screen-md">
            <h3 className="text-center text-3xl font-bold py-5">Contact Me</h3>
            <p className="text-center px-5 text-md py-2 leading-8 text-gray-700 dark:text-sky-500">
              {" "}
              Feel free to contact me! For more informations and for your
              business career
            </p>
            <form action="#" className="space-y-8 py-10">
              <div>
                <label
                  for="email"
                  className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"
                >
                  Your email
                </label>
                <input
                  type="email"
                  id="email"
                  className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-sky-500 dark:border-cyan-400 dark:placeholder-white dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                  placeholder="youremail@yourwebmail.com"
                  required
                />
              </div>
              <div>
                <label
                  for="subject"
                  className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"
                >
                  Subject
                </label>
                <input
                  type="text"
                  id="subject"
                  className="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-sky-500 dark:border-cyan-400 dark:placeholder-white dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                  placeholder="Let me know how can i help you"
                  required
                />
              </div>
              <div className="sm:col-span-2">
                <label
                  for="message"
                  className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"
                >
                  Your message
                </label>
                <textarea
                  id="message"
                  rows="6"
                  className="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-sky-500 dark:border-cyan-400 dark:placeholder-white dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                  placeholder="Talk to me ;)"
                ></textarea>
              </div>
              <button
                type="submit"
                className="mt-10 py-3 px-20 text-sm font-medium text-center text-white rounded-lg bg-sky-500 sm:w-fit hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
              >
                Send message
              </button>
            </form>
            
          </div>
        </section>
        <section>
        <div>
            <button
                type="backToTop"
                className="mt-10 py-3 px-4 text-sm font-medium text-center text-white rounded-full bg-sky-500 sm:w-fit hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
              >⏏</button>
            </div>
        </section>
      </main>
      <footer className="bg-sky-500 dark:bg-white">
        <div className="p-10  flex justify-center gap-20 text-white dark:text-sky-500">
          <h3>© 2022 Hassen Bouzidi | All Rights reserved</h3>
        </div>
      </footer>
    </div>
  );
}
